-- Cabin Concierge TV - property/company alerts (e.g. burn bans, pollen advisories, water conservation)
-- Run after supabase_org_scoped_access.sql.
--
-- Alerts follow the same property_id/org_id scoping as discounts: a non-NULL
-- property_id targets one property; a NULL property_id with a matching
-- org_id applies to every property in that organization; NULL property_id
-- and NULL org_id applies globally. Only is_active = true rows are returned.

CREATE TABLE IF NOT EXISTS public.property_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id UUID,
    property_id TEXT REFERENCES public.properties(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    severity TEXT NOT NULL DEFAULT 'notice' CHECK (severity IN ('notice', 'warning', 'critical')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INT DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.property_alerts ENABLE ROW LEVEL SECURITY;

-- No public/anon SELECT policy is created here; the Roku app must use the
-- device-gated get_active_alerts RPC below, matching house_rules,
-- recommendations, checkout_tasks, and discounts.

CREATE OR REPLACE FUNCTION public.get_active_alerts(p_device_id TEXT, p_device_token TEXT)
RETURNS TABLE (message TEXT, severity TEXT)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
    WITH authorized_device AS (
        SELECT p.id AS property_id, p.org_id
        FROM roku_devices d
        JOIN properties p ON p.id = d.property_id
        WHERE d.device_id = p_device_id
          AND d.revoked_at IS NULL
          AND extensions.crypt(p_device_token, d.credential_hash) = d.credential_hash
    )
    SELECT pa.message, pa.severity
    FROM property_alerts pa, authorized_device ad
    WHERE pa.is_active = true
      AND (
        pa.property_id = ad.property_id
        OR (pa.property_id IS NULL AND pa.org_id = ad.org_id)
        OR (pa.property_id IS NULL AND pa.org_id IS NULL)
      )
    ORDER BY pa.sort_order ASC;
$$;

REVOKE ALL ON FUNCTION public.get_active_alerts(TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_active_alerts(TEXT, TEXT) TO anon;

NOTIFY pgrst, 'reload schema';
