-- ===================================================================
-- Cabin Concierge TV - Supabase Database Schema & Initial Seed Data
-- ===================================================================
-- Run this script in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Create 'properties' Table
CREATE TABLE IF NOT EXISTS public.properties (
    id TEXT PRIMARY KEY,
    pin VARCHAR(10) NOT NULL UNIQUE,
    name TEXT NOT NULL,
    tagline TEXT,
    location TEXT,
    address TEXT,
    guest_name TEXT,
    stay_dates TEXT,
    wifi_network TEXT,
    wifi_password TEXT,
    wifi_speed TEXT,
    check_in_time TEXT DEFAULT '4:00 PM',
    check_out_time TEXT DEFAULT '11:00 AM',
    trash_day TEXT,
    quiet_hours TEXT DEFAULT '10:00 PM – 8:00 AM',
    max_occupancy INT DEFAULT 8,
    host_name TEXT,
    host_phone TEXT,
    emergency_contact TEXT DEFAULT 'Dial 911',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast PIN lookups
CREATE INDEX IF NOT EXISTS idx_properties_pin ON public.properties(pin);

-- 2. Create 'house_rules' Table
CREATE TABLE IF NOT EXISTS public.house_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id TEXT REFERENCES public.properties(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    summary TEXT,
    details TEXT,
    fine TEXT,
    sort_order INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create 'recommendations' Table
CREATE TABLE IF NOT EXISTS public.recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id TEXT REFERENCES public.properties(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    distance TEXT,
    rating TEXT,
    price TEXT,
    description TEXT,
    host_tip TEXT,
    sort_order INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create 'checkout_tasks' Table
CREATE TABLE IF NOT EXISTS public.checkout_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id TEXT REFERENCES public.properties(id) ON DELETE CASCADE,
    task_key TEXT NOT NULL,
    title TEXT NOT NULL,
    time_estimate TEXT,
    is_required BOOLEAN DEFAULT TRUE,
    sort_order INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Create 'guest_feedback' Table
CREATE TABLE IF NOT EXISTS public.guest_feedback (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    property_id TEXT,
    property_pin TEXT,
    rating INT CHECK (rating >= 1 AND rating <= 5),
    feedback_text TEXT,
    submitted_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===================================================================
-- Row Level Security (RLS) Policies
-- Enables public read access and guest feedback insertions via Anon Key
-- ===================================================================

ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.house_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.checkout_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guest_feedback ENABLE ROW LEVEL SECURITY;

-- Allow anonymous read access
CREATE POLICY "Allow public read access on properties" ON public.properties FOR SELECT USING (true);
CREATE POLICY "Allow public read access on house_rules" ON public.house_rules FOR SELECT USING (true);
CREATE POLICY "Allow public read access on recommendations" ON public.recommendations FOR SELECT USING (true);
CREATE POLICY "Allow public read access on checkout_tasks" ON public.checkout_tasks FOR SELECT USING (true);

-- Allow anonymous inserts for feedback
CREATE POLICY "Allow public insert on guest_feedback" ON public.guest_feedback FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read access on guest_feedback" ON public.guest_feedback FOR SELECT USING (true);

-- ===================================================================
-- Seed Initial Sample Data
-- ===================================================================

INSERT INTO public.properties (id, pin, name, tagline, location, address, guest_name, stay_dates, wifi_network, wifi_password, wifi_speed, check_in_time, check_out_time, trash_day, quiet_hours, max_occupancy, host_name, host_phone, emergency_contact)
VALUES
(
    'reflections-01',
    '7421',
    'Reflections',
    'Your Private Mountain & Cedar Sanctuary',
    'Hochatown, Oklahoma',
    '124 Whispering Pines Trl, Hochatown, OK 74728',
    'The Henderson Family',
    'October 14 – October 18',
    'BBVC2024',
    'BBVC2024',
    '300 Mbps',
    '4:00 PM',
    '11:00 AM',
    'Mondays – Wednesdays – Fridays',
    '10:00 PM – 8:00 AM',
    8,
    'Reservations',
    '(580) 306-2287',
    'Dial 911'
),
(
    'cedar-ridge-02',
    '8832',
    'Cedar Ridge Mountain Retreat',
    'Panoramic Forest Views & High-End Luxury Spa',
    'Hochatown Foothills, Oklahoma',
    '419 Ouachita Ridge Dr, Hochatown, OK 74728',
    'The Miller Family & Friends',
    'July 18 – July 23',
    'CedarRidge_Ultra5G',
    'CedarMountain4K!',
    '650 Mbps (Fiber)',
    '4:00 PM',
    '11:00 AM',
    'Mondays & Thursdays',
    '10:00 PM – 7:30 AM',
    10,
    'Marcus & Elena Vance',
    '(580) 555-0842',
    'Hochatown Fire Dept: (580) 584-2400'
),
(
    'timber-creek-03',
    '1945',
    'Timber Creek Riverfront Lodge',
    'Private Riverfront Access & Wrap-Around Deck',
    'Broken Bow Riverfront, Oklahoma',
    '88 Mountain Fork Way, Broken Bow, OK 74728',
    'Sarah & David Jenkins',
    'Sept 10 – Sept 14',
    'Riverfront_Fiber_Guest',
    'RiverPineCabins99',
    '500 Mbps (Fiber)',
    '3:30 PM',
    '11:00 AM',
    'Wednesdays & Saturdays',
    '10:00 PM – 8:00 AM',
    6,
    'Sarah & David Sterling',
    '(580) 555-0194',
    'Broken Bow Police: (580) 584-3310'
)
ON CONFLICT (id) DO NOTHING;

-- Seed Global House Rules
INSERT INTO public.house_rules (property_id, title, category, summary, details, fine, sort_order)
VALUES
(NULL, 'Hot Tub Guidelines & Care', 'Safety & Amenities', 'Shower before use, secure thermal cover after each soak, max 104°F.', '1. Rinse off lotions and oils before soaking. 2. Keep the thermal cover latched down when not in use. 3. Strictly NO glass containers near the spa. 4. Do not turn off the main circuit breaker.', '$250 drain & sanitization fee for glass or contamination.', 1),
(NULL, 'Trash & Wildlife Safety', 'Cleanliness & Environment', 'Lock all garbage in the steel bear bins. Never leave bags on open decks.', 'Hochatown is active black bear territory. All household trash must be sealed in heavy bags and locked inside the outdoor bear bin by the driveway.', '$150 HOA cleaning fine for open bags left outdoors.', 2),
(NULL, 'Strict Quiet Hours (10:00 PM – 8:00 AM)', 'Neighborhood Courtesy', 'Turn off outdoor speakers and move lively gatherings inside after 10 PM.', 'Sound travels across the mountain hollows. Please keep patio conversation quiet and respect neighboring woodland cabins.', 'Sheriff noise citations are billed directly to guest.', 3),
(NULL, 'Indoor Fireplace & Fire Pit Safety', 'Safety & Fire', 'Use only seasoned hardwood. Fully extinguish pit with hose before sleep.', 'Firewood is stacked on the side porch. Never burn trash or pine needles. Ensure coals are cold to touch before retiring.', 'Never use liquid fire starters or accelerants indoors.', 4),
(NULL, '100% Smoke-Free Interior', 'Health & Safety', 'Smoking and vaping permitted ONLY at the outdoor gravel fire pit.', 'No smoking, vaping, or incense inside the cabin or screened porches. Dispose of butts safely in the metal ashtray.', '$500 deep-cleaning and ozone restoration fee.', 5);

-- Seed Recommendations
INSERT INTO public.recommendations (property_id, name, category, distance, rating, price, description, host_tip, sort_order)
VALUES
(NULL, 'Friends Trail Loop', 'Hiking & Nature', '1.8 miles (4 min drive)', '4.9 / 5', 'Free', 'Scenic 1.5-mile loop along the Mountain Fork River rapids with rock outcroppings and crystal-clear swimming holes.', 'Start early before 9:30 AM to catch the morning river mist and avoid peak traffic. Sturdy hiking shoes recommended.', 1),
(NULL, 'Grateful Head Pizza Oven & Tap Room', 'Dining & Drinks', '2.4 miles (5 min drive)', '4.8 / 5', '$$', 'Artisan wood-fired pizzas with a lively rustic beer garden under string lights in Hochatown.', 'Try the "Tree Hugger" or "Dire Wolf" specialty pies. Arrive early on weekends!', 2),
(NULL, 'Beavers Bend Marina & Boat Rentals', 'Lake & Marina', '5.2 miles (10 min drive)', '4.7 / 5', '$$$', 'Luxury tritoon pontoon rentals, double-decker slide boats, jet skis, and paddleboards on Broken Bow Lake.', 'Book pontoon boats at least 48 hours in advance for sunset cruises. Free parking with boat reservation.', 3),
(NULL, 'Mountain Fork Brewery', 'Breweries & Wineries', '2.9 miles (6 min drive)', '4.8 / 5', '$$', 'Family-friendly craft brewery brewed with Ouachita mountain spring water. Great flatbreads and giant lawn games.', 'Host favorite: Sneaky Snake Belgian Ale and Loaded Elk Jalapeño Popper Dip. Live music on Fridays.', 4),
(NULL, 'Cedar Creek Golf Course', 'Family Fun & Sports', '6.1 miles (12 min drive)', '4.6 / 5', '$$$', 'Pristine 18-hole championship course nestled along Broken Bow Lake with towering pine fairways.', 'Call ahead for morning tee times. Driving range offers spectacular mountain lake vistas.', 5),
(NULL, 'Girls Gone Wine', 'Breweries & Wineries', '2.2 miles (5 min drive)', '4.9 / 5', '$$', 'Boutique winery tasting room and sassy gift shop with complimentary tastings in the heart of Hochatown.', 'Fun, upbeat vibe. Great place to pick up a chilled bottle of local wine for evening hot tub soaks.', 6);

-- Seed Checkout Tasks
INSERT INTO public.checkout_tasks (property_id, task_key, title, time_estimate, is_required, sort_order)
VALUES
(NULL, 'task1', 'Start the Dishwasher (Normal Cycle with Pod)', '3 min', TRUE, 1),
(NULL, 'task2', 'Take Tied Trash to Bear-Proof Bin', '5 min', TRUE, 2),
(NULL, 'task3', 'Set Thermostat to Eco (74°F Cool / 65°F Heat)', '1 min', TRUE, 3),
(NULL, 'task4', 'Secure & Latch Hot Tub Thermal Cover', '2 min', TRUE, 4),
(NULL, 'task5', 'Lock All Sliding Patio Doors & Windows', '3 min', TRUE, 5),
(NULL, 'task6', 'Place Used Towels in Bathtub', '2 min', FALSE, 6);

